### ISSUE TITLE
Not able to compile the scripts

### ISSUE THREAD

**Issue by abstruse123** [selyunin/bno055_usb_stick_py#2]
Hi!

I followed the procedure as mentioned in your page to run the python driver for BNO055 usb stick (red color model) with the switch kept in the 'H' position as given in its manual. I am able to get the data in Windows using DD 2.0 UI.

I connected the BNO055 USB stick to my PC running Ubuntu 16.04 LTS. 
Pl. see the below terminal commands & their responses showing the errors. 
Kindly help to resolve the issue. Thank you.
The python version is 3.7.1.

_I attempted the same process by creating an environment in conda, but the error is the same._

```
raghavan@raghavan-desktop:~$ cd /home/raghavan/BNO055/bno055_usb_stick_py-master/bno055_usb_stick_py
raghavan@raghavan-desktop:~/BNO055/bno055_usb_stick_py-master/bno055_usb_stick_py$ ls
97-ttyacm.rules  bno055_usb_stick.py                     __init__.py
bno055.json      disable_modem_manager_bno_usb_stick.py  one.py
bno055.py        examples.py
raghavan@raghavan-desktop:~/BNO055/bno055_usb_stick_py-master/bno055_usb_stick_py$ python disable_modem_manager_bno_usb_stick.py
[sudo] password for raghavan: 
copying rules file: /home/raghavan/BNO055/bno055_usb_stick_py-master/bno055_usb_stick_py/97-ttyacm.rules to /etc/udev/rules.d
raghavan@raghavan-desktop:~/BNO055/bno055_usb_stick_py-master/bno055_usb_stick_py$ ls
97-ttyacm.rules  bno055_usb_stick.py                     __init__.py
bno055.json      disable_modem_manager_bno_usb_stick.py  one.py
bno055.py        examples.py
raghavan@raghavan-desktop:~/BNO055/bno055_usb_stick_py-master/bno055_usb_stick_py$ python one.py
Traceback (most recent call last):
  File "one.py", line 3, in <module>
    bno_usb_stick = BnoUsbStick()
  File "/home/raghavan/miniconda3/lib/python3.7/site-packages/bno055_usb_stick_py/bno055_usb_stick.py", line 37, in __init__
    self.autodetect()
  File "/home/raghavan/miniconda3/lib/python3.7/site-packages/bno055_usb_stick_py/bno055_usb_stick.py", line 77, in autodetect
    raise BnoException("BNO USB Stick not detected!")
bno055_usb_stick_py.bno055_usb_stick.BnoException: BNO USB Stick not detected!
raghavan@raghavan-desktop:~/BNO055/bno055_usb_stick_py-master/bno055_usb_stick_py$ sudo python one.py
  File "one.py", line 6
    print(f"bno data: {packet}")
                              ^
SyntaxError: invalid syntax
raghavan@raghavan-desktop:~/BNO055/bno055_usb_stick_py-master/bno055_usb_stick_py$ python examples.py
Traceback (most recent call last):
  File "examples.py", line 46, in <module>
    example_register_read()
  File "examples.py", line 8, in example_register_read
    bno_usb_stick = BnoUsbStick()
  File "/home/raghavan/miniconda3/lib/python3.7/site-packages/bno055_usb_stick_py/bno055_usb_stick.py", line 37, in __init__
    self.autodetect()
  File "/home/raghavan/miniconda3/lib/python3.7/site-packages/bno055_usb_stick_py/bno055_usb_stick.py", line 77, in autodetect
    raise BnoException("BNO USB Stick not detected!")
bno055_usb_stick_py.bno055_usb_stick.BnoException: BNO USB Stick not detected!
raghavan@raghavan-desktop:~/BNO055/bno055_usb_stick_py-master/bno055_usb_stick_py$ sudo python examples.py
  File "examples.py", line 11
    print(f"bno chip id addr: 0x{reg_addr:02X}, value: 0x{reg_val:02X}")
raghavan@raghavan-desktop:~/BNO055/bno055_usb_stick_py-master/bno055_usb_stick_py$ python
Python 3.7.1 (default, Dec 14 2018, 19:46:24) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys; sys.version_info
sys.version_info(major=3, minor=7, micro=1, releaselevel='final', serial=0)
```
I have used the same examples.py file as provided by you. The code for one.py is as follows:
`
from bno055_usb_stick_py import BnoUsbStick

bno_usb_stick = BnoUsbStick()
bno_usb_stick.activate_streaming()
for packet in bno_usb_stick.recv_streaming_generator(num_packets=10):
    print(f"bno data: {packet}")
`
                                                                      ^

**Comment by selyunin** [comment]
Hi Raghavan,

As far as I can see, there could be several problems.
First, it seems to me that your `user` python version and `sudo python` versions are **not** the same.
Could you please check, in your terminal:
```bash
sudo python
```
and then in the `sudo python` prompt print `python` version:
```python
import sys; sys.version_info
```

Second, `BnoUsbStick` is not detected in your system. Are you running native Ubuntu or via virtual machine (e.g. VirtualBox or VMWare)? If you are using virtual machine option, make sure that USB devices are detected in your VM.

In addition, could you post the output of the following bash commands:
```bash
ls /dev/ttyACM*
```
and 
```bash
udevadm info -q all `ls /dev/ttyACM*`
```

**Comment by abstruse123** [comment]
Hi! Thanks for the response.

**I have executed the commands suggested by you and the results are as follows.
Kindly go through and suggest solution. Thank you.**

Yes, the versions of 'user python' and 'sudo python' are different.

```
raghavan@raghavan-desktop:~$ sudo python
[sudo] password for raghavan: 
Python 2.7.12 (default, Nov 12 2018, 14:36:49) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 
raghavan@raghavan-desktop:~$ python
Python 3.7.1 (default, Dec 14 2018, 19:46:24) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

bash commands and their outputs

```
raghavan@raghavan-desktop:~$ ls /dev/ttyACM*
/dev/ttyACM0


raghavan@raghavan-desktop:~$ udevadm info -q all `ls /dev/ttyACM*`
P: /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.6/2-1.6:1.0/tty/ttyACM0
N: ttyACM0
S: serial/by-id/usb-Bosch_Sensortec_Bosch_Sensortec_BNO_stick_001-if00
S: serial/by-path/pci-0000:00:1d.0-usb-0:1.6:1.0
E: DEVLINKS=/dev/serial/by-id/usb-Bosch_Sensortec_Bosch_Sensortec_BNO_stick_001-if00 /dev/serial/by-path/pci-0000:00:1d.0-usb-0:1.6:1.0
E: DEVNAME=/dev/ttyACM0
E: DEVPATH=/devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.6/2-1.6:1.0/tty/ttyACM0
E: ID_BUS=usb
E: ID_MM_CANDIDATE=1
E: ID_MM_DEVICE_IGNORE=1
E: ID_MODEL=Bosch_Sensortec_BNO_stick
E: ID_MODEL_ENC=Bosch\x20Sensortec\x20BNO\x20stick
E: ID_MODEL_FROM_DATABASE=5 Series/3400 Series Chipset USB2 Enhanced Host Controller
E: ID_MODEL_ID=80c1
E: ID_PATH=pci-0000:00:1d.0-usb-0:1.6:1.0
E: ID_PATH_TAG=pci-0000_00_1d_0-usb-0_1_6_1_0
E: ID_PCI_CLASS_FROM_DATABASE=Serial bus controller
E: ID_PCI_INTERFACE_FROM_DATABASE=EHCI
E: ID_PCI_SUBCLASS_FROM_DATABASE=USB controller
E: ID_REVISION=0100
E: ID_SERIAL=Bosch_Sensortec_Bosch_Sensortec_BNO_stick_001
E: ID_SERIAL_SHORT=001
E: ID_TYPE=generic
E: ID_USB_CLASS_FROM_DATABASE=Communications
E: ID_USB_DRIVER=cdc_acm
E: ID_USB_INTERFACES=:020201:0a0000:
E: ID_USB_INTERFACE_NUM=00
E: ID_VENDOR=Bosch_Sensortec
E: ID_VENDOR_ENC=Bosch\x20Sensortec
E: ID_VENDOR_FROM_DATABASE=Thesycon Systemsoftware & Consulting GmbH
E: ID_VENDOR_ID=152a
E: MAJOR=166
E: MINOR=0
E: SUBSYSTEM=tty
E: TAGS=:systemd:
E: USEC_INITIALIZED=177050848
```

**Comment by selyunin** [comment]
OK, you actually do not need `sudo` to launch the scripts (if you are member of the `dialout` group).

The output of `udevadm` seems fine to me.

Does reading a single register work? What is the output of the following, do you get any errors?

```python
from bno055_usb_stick_py import BnoUsbStick
bno_usb_stick = BnoUsbStick()
reg_addr = 0x00
reg_val = bno_usb_stick.read_register(reg_addr)
print(f"bno chip id addr: 0x{reg_addr:02X}, value: 0x{reg_val:02X}")
```

**Comment by abstruse123** [comment]
Hi!
I had to make a small change to the code as follows, without which it didn't compile:
```
from bno055_usb_stick import BnoUsbStick
bno_usb_stick = BnoUsbStick()
reg_addr = 0x00
reg_val = bno_usb_stick.read_register(reg_addr)
print(f"bno chip id addr: 0x{reg_addr:02X}, value: 0x{reg_val:02X}")
```

However, this is the output that I got in python shell. Pl. see what is the issue.
```

Python 3.5.2 (default, Nov 12 2018, 13:43:14) 
[GCC 5.4.0 20160609] on linux
Type "copyright", "credits" or "license()" for more information.
>>> 
====== RESTART: /home/raghavan/BNO055_python/bno055_usb_stick_py/ex1.py ======
Traceback (most recent call last):
  File "/home/raghavan/BNO055_python/bno055_usb_stick_py/ex1.py", line 1, in <module>
    from bno055_usb_stick import BnoUsbStick
  File "/home/raghavan/BNO055_python/bno055_usb_stick_py/bno055_usb_stick.py", line 151
    info_str = f"SHUTTLE_ID: {shuttle_id};\t\tHARDWARE_ID: {hardware_id};" + \
                                                                         ^
SyntaxError: invalid syntax
>>> 
```

**Comment by selyunin** [comment]
Yep, you to use at least Python 3.6 -- the formatted strings `f"this is my string  with {my_variable}"` works only on Python 3.6 onwards, and I use this syntax in the code.
You need to resolve the dependencies first -- install python 3.6 on a linux machine, and additional required packages.

**Comment by selyunin** [comment]
Closing issue as obsolete
